version: "3.3"

services:
  nginx:
    build: docker/nginx
    ports:
      - 8088:80
    depends_on:
      - phpfpm
    volumes:
      - ./src:${APP_PATH_CONTAINER}

  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpfpm:
    build: docker/phpfpm
    volumes:
      - ./src:${APP_PATH_CONTAINER}
      - ${DB_PATH_HOST}/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 9010:9000
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    links:
      - db

#  composer:
#    image: composer:1.7
#    volumes:
#      - ./src:${APP_PATH_CONTAINER}
#    working_dir: ${APP_PATH_CONTAINER}
#    command: composer install

volumes:
  mysql_data: