version: "3.3"

services:
  nginx:
    build: docker/nginx
    ports:
      - 8088:80
    depends_on:
      - phpfpm
    volumes:
      - app-sync:${APP_PATH_CONTAINER}:nocopy

  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpfpm:
    build: docker/phpfpm
    volumes:
      - app-sync:${APP_PATH_CONTAINER}:nocopy
      - ${DB_PATH_HOST}/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 9010:9000
    links:
      - db

  composer:
    image: composer:1.7
    volumes:
      - app-sync:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}:nocopy
    command: composer install

volumes:
  mysql_data:
  app-sync:
    external: true