version: "3.3"

services:
  nginx:
    depends_on:
      - phpfpm
    volumes:
      - englishtest-sync:/var/www/html:nocopy

  phpfpm:
    volumes:
      - englishtest-sync:/var/www/html:nocopy

#  composer:
#    volumes:
#      - app-sync:${APP_PATH_CONTAINER}

volumes:
  englishtest-sync:
    external: true