version: "3.3"

services:
  nginx:
    volumes:
      - app-sync:${APP_PATH_CONTAINER}:nocopy

  phpfpm:
    volumes:
      - app-sync:${APP_PATH_CONTAINER}:nocopy

#  composer:
#    volumes:
#      - app-sync:${APP_PATH_CONTAINER}

volumes:
  app-sync:
    external: true