version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8088:80
    depends_on:
      - phpfpm
    volumes:
      - .:${APP_PATH_CONTAINER}:ro

  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  phpfpm:
    build:
      context: .
      dockerfile: docker/phpfpm/Dockerfile
    volumes:
      - .:${APP_PATH_CONTAINER}:rw,cached
    ports:
      - 9010:9000
    environment:
      XDEBUG_CONFIG: >-
        remote_enable=1
        remote_host=host.docker.internal
        remote_connect_back=1
        remote_port=9000
        idekey=PHPSTORM
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    depends_on:
      - db

volumes:
  mysql_data:
